const PERMISSIONS = Object.freeze({
    ADMIN_ACCOUNTS_READ: "ADMIN_ACCOUNTS_READ",
    ADMIN_ACCOUNTS_MANAGE: "ADMIN_ACCOUNTS_MANAGE",
    ADMIN_SESSIONS_READ: "ADMIN_SESSIONS_READ",
    ADMIN_SESSIONS_REVOKE: "ADMIN_SESSIONS_REVOKE",
    AUDIT_LOG_READ: "AUDIT_LOG_READ",
    DASHBOARD_READ: "DASHBOARD_READ",
    ORDERS_READ: "ORDERS_READ",
    ORDERS_MANAGE: "ORDERS_MANAGE",
    WALLET_READ: "WALLET_READ",
    WALLET_APPROVE: "WALLET_APPROVE",
    WALLET_REJECT: "WALLET_REJECT",
    USERS_READ: "USERS_READ",
    USERS_MANAGE: "USERS_MANAGE",
    CATALOG_READ: "CATALOG_READ",
    CATALOG_MANAGE: "CATALOG_MANAGE",
    MEDIA_READ: "MEDIA_READ",
    MEDIA_MANAGE: "MEDIA_MANAGE",
    DESIGN_STUDIO_READ: "DESIGN_STUDIO_READ",
    DESIGN_STUDIO_MANAGE: "DESIGN_STUDIO_MANAGE",
    DESIGN_STUDIO_EXPORT: "DESIGN_STUDIO_EXPORT",
    SITE_CONTENT_READ: "SITE_CONTENT_READ",
    SITE_CONTENT_MANAGE: "SITE_CONTENT_MANAGE",
    CAMPAIGNS_READ: "CAMPAIGNS_READ",
    CAMPAIGNS_MANAGE: "CAMPAIGNS_MANAGE",
    PROMOS_READ: "PROMOS_READ",
    PROMOS_MANAGE: "PROMOS_MANAGE",
    PAYMENT_METHODS_READ: "PAYMENT_METHODS_READ",
    PAYMENT_METHODS_MANAGE: "PAYMENT_METHODS_MANAGE",
    SUPPLIERS_READ: "SUPPLIERS_READ",
    SUPPLIERS_MANAGE: "SUPPLIERS_MANAGE",
    SUPPLIER_MAPPINGS_MANAGE: "SUPPLIER_MAPPINGS_MANAGE",
    OWNER_ROUTING_MANAGE: "OWNER_ROUTING_MANAGE",
    FULFILLMENT_READ: "FULFILLMENT_READ",
    FULFILLMENT_EXECUTE: "FULFILLMENT_EXECUTE",
    FULFILLMENT_RESOLVE: "FULFILLMENT_RESOLVE",
    SETTINGS_READ: "SETTINGS_READ",
    SETTINGS_MANAGE: "SETTINGS_MANAGE",
    SUPPORT_READ: "SUPPORT_READ",
    SUPPORT_MANAGE: "SUPPORT_MANAGE",
    LIVE_CHAT_READ: "LIVE_CHAT_READ",
    LIVE_CHAT_MANAGE: "LIVE_CHAT_MANAGE"
});

const ROLES = Object.freeze({
    OWNER: "OWNER",
    OPERATIONS: "OPERATIONS",
    FINANCE: "FINANCE",
    SUPPORT: "SUPPORT",
    CATALOG: "CATALOG"
});

const STATUSES = Object.freeze({
    ACTIVE: "ACTIVE",
    DISABLED: "DISABLED"
});

const ROLE_PERMISSIONS = Object.freeze({
    OWNER: Object.freeze(Object.values(PERMISSIONS)),
    OPERATIONS: Object.freeze([
        PERMISSIONS.DASHBOARD_READ,
        PERMISSIONS.ORDERS_READ,
        PERMISSIONS.ORDERS_MANAGE,
        PERMISSIONS.SUPPLIERS_READ,
        PERMISSIONS.FULFILLMENT_READ,
        PERMISSIONS.FULFILLMENT_EXECUTE,
        PERMISSIONS.FULFILLMENT_RESOLVE,
        PERMISSIONS.USERS_READ,
        PERMISSIONS.SUPPORT_READ,
        PERMISSIONS.SUPPORT_MANAGE,
        PERMISSIONS.LIVE_CHAT_READ,
        PERMISSIONS.LIVE_CHAT_MANAGE
    ]),
    FINANCE: Object.freeze([
        PERMISSIONS.DASHBOARD_READ,
        PERMISSIONS.ORDERS_READ,
        PERMISSIONS.SUPPLIERS_READ,
        PERMISSIONS.FULFILLMENT_READ,
        PERMISSIONS.WALLET_READ,
        PERMISSIONS.WALLET_APPROVE,
        PERMISSIONS.WALLET_REJECT,
        PERMISSIONS.PAYMENT_METHODS_READ,
        PERMISSIONS.PAYMENT_METHODS_MANAGE,
        PERMISSIONS.PROMOS_READ
    ]),
    SUPPORT: Object.freeze([
        PERMISSIONS.USERS_READ,
        PERMISSIONS.ORDERS_READ,
        PERMISSIONS.FULFILLMENT_READ,
        PERMISSIONS.SUPPORT_READ,
        PERMISSIONS.SUPPORT_MANAGE,
        PERMISSIONS.LIVE_CHAT_READ,
        PERMISSIONS.LIVE_CHAT_MANAGE
    ]),
    CATALOG: Object.freeze([
        PERMISSIONS.DASHBOARD_READ,
        PERMISSIONS.CATALOG_READ,
        PERMISSIONS.CATALOG_MANAGE,
        PERMISSIONS.SUPPLIERS_READ,
        PERMISSIONS.SUPPLIER_MAPPINGS_MANAGE,
        PERMISSIONS.MEDIA_READ,
        PERMISSIONS.MEDIA_MANAGE,
        PERMISSIONS.DESIGN_STUDIO_READ,
        PERMISSIONS.DESIGN_STUDIO_MANAGE,
        PERMISSIONS.DESIGN_STUDIO_EXPORT,
        PERMISSIONS.SITE_CONTENT_READ,
        PERMISSIONS.SITE_CONTENT_MANAGE,
        PERMISSIONS.CAMPAIGNS_READ,
        PERMISSIONS.CAMPAIGNS_MANAGE,
        PERMISSIONS.PROMOS_READ,
        PERMISSIONS.PROMOS_MANAGE
    ])
});

function getPermissionsForRole(role) {
    return ROLE_PERMISSIONS[String(role || "").toUpperCase()] || [];
}

function hasPermission(admin, permission) {
    if (!admin || !permission) return false;
    return getPermissionsForRole(admin.role).includes(permission);
}

function requireAdminPermission(permission) {
    return (req, res, next) => {
        if (hasPermission(req.admin, permission)) return next();

        return res.status(403).json({
            success: false,
            error: "ADMIN_PERMISSION_DENIED",
            permission,
            message: "Admin permission denied"
        });
    };
}

module.exports = {
    PERMISSIONS,
    ROLES,
    ROLE_PERMISSIONS,
    STATUSES,
    getPermissionsForRole,
    hasPermission,
    requireAdminPermission
};
