"use strict";

const mongoose = require("mongoose");
const CatalogPackage = require("../models/CatalogPackage");
const CatalogProduct = require("../models/CatalogProduct");
const Supplier = require("../models/Supplier");
const Mapping = require("../models/SupplierProductMapping");
const Offer = require("../models/SupplierCatalogOffer");
const Availability = require("../models/SupplierOfferAvailability");
const SupplierCatalogProduct = require("../models/SupplierCatalogProduct");
const Selection = require("../models/StoreCatalogSelection");
const { getSupplierAdapter } = require("./supplierAdapterRegistry");
const { supportsFazerCardsMapping } = require("./suppliers/fazercardsFulfillmentProcessor");
const { hasFazerCardsInputContract } = require("./suppliers/fazercardsInputFormatters");
const { contractFromSupplierCatalog } = require("./suppliers/fazercardsFulfillmentContractService");
const { writeAdminAudit, ADMIN_AUDIT_ACTIONS } = require("./adminAuditService");
const { isCustomerMarketCompatible, supplierMarketCompatibility } = require("./supplierFulfillmentEligibilityService");
const { assessExistingPreparedRoute } = require("./supplierCatalog/supplierRoutePreparationService");

const clean = value => String(value == null ? "" : value).trim();
const upper = value => clean(value).toUpperCase();
const lower = value => clean(value).toLowerCase();
const id = value => clean(value?._id || value);

class StorePackageActivationError extends Error {
    constructor(code, message, statusCode = 409, details = {}) { super(message); this.name = "StorePackageActivationError"; this.code = code; this.statusCode = statusCode; this.details = details; }
}

function approvedCost(mapping) { const cost = Number(mapping?.supplierCostAuthority?.rawSupplierCost); return Number.isFinite(cost) && cost >= 0 && Boolean(mapping?.supplierCostAuthority?.supplierCurrency) && Boolean(mapping?.supplierCostAuthority?.capturedAt); }
function exactInputContract(mapping) { return upper(mapping?.supplierCode) === "FAZERCARDS" && lower(mapping?.productCode) === "mlbb" && clean(mapping?.supplierProductCode) === "mobile_legends_global" && hasFazerCardsInputContract(mapping.productCode); }
function activationBlockers({ selection, mapping, customerMarket, conflicts = [], preCommercial = { ready: false, blockers: ["PRECOMMERCIAL_READINESS_UNAVAILABLE"] } }) {
    const market = upper(customerMarket), blockers = [], selected = selection?.packages?.some(item => id(item.supplierProductMappingId) === id(mapping) && upper(item.packageCode) === upper(mapping?.packageCode));
    if (!selection || selection.status !== "ACTIVE" || !selected) blockers.push("STORE_CATALOG_PACKAGE_NOT_SELECTED");
    if (id(selection?.supplierId) !== id(mapping?.supplierId) || lower(selection?.productCode) !== lower(mapping?.productCode) || upper(selection?.supplierMarket) !== upper(mapping?.region)) blockers.push("STORE_CATALOG_ROUTE_SCOPE_MISMATCH");
    if (!selection?.sellingRegions?.includes(market)) blockers.push("SELLING_MARKET_NOT_SELECTED");
    if (preCommercial.ready !== true) blockers.push(...(preCommercial.blockers || ["PRECOMMERCIAL_READINESS_UNAVAILABLE"]));
    if (conflicts.length) blockers.push("CONFLICTING_PRIMARY_ROUTE");
    return [...new Set(blockers)];
}
function sourceLock({ selection, mapping, supplier, product, pkg, offer, supplierProduct, fulfillmentContract, availability, customerMarket }) { return { selectionId:id(selection),selectionDecisionVersion:Number(selection?.decisionVersion||0),mappingId:id(mapping),mappingUpdatedAt:mapping?.updatedAt||null,supplierId:id(supplier),supplierUpdatedAt:supplier?.updatedAt||null,supplierMarket:upper(mapping?.region),productCode:lower(mapping?.productCode),productUpdatedAt:product?.updatedAt||null,packageCode:upper(mapping?.packageCode),customerMarket:upper(customerMarket),packageUpdatedAt:pkg?.updatedAt||null,offerSourceRevision:offer?.sourceRevision||"",supplierProductSourceHash:supplierProduct?.rawSnapshotHash||"",supplierProductContractFingerprint:fulfillmentContract?.fingerprint||"",availabilityObservedAt:availability?.observedAt||null}; }
function assertSourceLock(expected = {}, actual = {}) { const date=value=>value?new Date(value).getTime():0,same=clean(expected.selectionId)===actual.selectionId&&Number(expected.selectionDecisionVersion)===actual.selectionDecisionVersion&&clean(expected.mappingId)===actual.mappingId&&date(expected.mappingUpdatedAt)===date(actual.mappingUpdatedAt)&&clean(expected.supplierId)===actual.supplierId&&date(expected.supplierUpdatedAt)===date(actual.supplierUpdatedAt)&&upper(expected.supplierMarket)===actual.supplierMarket&&lower(expected.productCode)===actual.productCode&&date(expected.productUpdatedAt)===date(actual.productUpdatedAt)&&upper(expected.packageCode)===actual.packageCode&&upper(expected.customerMarket)===actual.customerMarket&&date(expected.packageUpdatedAt)===date(actual.packageUpdatedAt)&&clean(expected.offerSourceRevision)===actual.offerSourceRevision&&clean(expected.supplierProductSourceHash)===actual.supplierProductSourceHash&&clean(expected.supplierProductContractFingerprint)===actual.supplierProductContractFingerprint&&date(expected.availabilityObservedAt)===date(actual.availabilityObservedAt); if(!same)throw new StorePackageActivationError("STORE_PACKAGE_ACTIVATION_STALE","Activation sources changed. Refresh and review before activating.",409,{actual}); }

function createStorePackageActivationService(models = {}, options = {}) {
    const M={Selection:models.Selection||Selection,Mapping:models.Mapping||Mapping,Supplier:models.Supplier||Supplier,Product:models.Product||CatalogProduct,Package:models.Package||CatalogPackage,Offer:models.Offer||Offer,SupplierCatalogProduct:models.SupplierCatalogProduct||SupplierCatalogProduct,Availability:models.Availability||Availability};
    const adapterResolver=options.adapterResolver||getSupplierAdapter,inputContractResolver=options.inputContractResolver,mappingSupportResolver=options.mappingSupportResolver,preCommercialReadinessResolver=options.preCommercialReadinessResolver,transaction=options.transaction||(async fn=>{const session=await mongoose.startSession();try{let result;await session.withTransaction(async()=>{result=await fn(session)});return result}finally{await session.endSession()}}),lean=(query,session)=>(session&&query.session?query.session(session):query).lean();
    async function load(input,session=null){const selection=await lean(M.Selection.findOne({_id:input.selectionId,status:"ACTIVE"}),session),mapping=await lean(M.Mapping.findOne({_id:input.mappingId,archivedAt:null}),session);if(!selection||!mapping)throw new StorePackageActivationError("STORE_PACKAGE_ACTIVATION_TARGET_NOT_FOUND","The selected Store Catalog route is unavailable.",404);const market=upper(input.customerMarket);const[supplier,product,pkg,offer,availability,conflicts]=await Promise.all([lean(M.Supplier.findById(mapping.supplierId),session),lean(M.Product.findOne({productCode:mapping.productCode}),session),lean(M.Package.findOne({productCode:mapping.productCode,packageCode:mapping.packageCode}),session),mapping.supplierCatalogOfferId?lean(M.Offer.findById(mapping.supplierCatalogOfferId),session):null,mapping.supplierCatalogOfferId?lean(M.Availability.findOne({supplierCatalogOfferId:mapping.supplierCatalogOfferId}),session):null,lean(M.Mapping.find({_id:{$ne:mapping._id},productCode:mapping.productCode,packageCode:mapping.packageCode,productionRole:"PRIMARY",enabled:true,archivedAt:null,$or:[{"fulfillmentEligibility.mode":"GLOBAL"},{"fulfillmentEligibility.mode":"CUSTOMER_MARKET_ALLOWLIST","fulfillmentEligibility.allowedCustomerMarkets":market}]}),session)]);const supplierProduct=offer?.supplierCatalogProductId?await lean(M.SupplierCatalogProduct.findById(offer.supplierCatalogProductId),session):null;const fulfillmentContract=contractFromSupplierCatalog({mapping,offer,supplierProduct});const adapter=supplier?adapterResolver(supplier):null;const resolverContext={offer,product,supplierProduct,fulfillmentContract};const inputContractReady=(inputContractResolver?inputContractResolver(mapping,resolverContext):Boolean(fulfillmentContract)||exactInputContract(mapping))===true,offerSupported=(mappingSupportResolver?mappingSupportResolver(mapping,resolverContext):Boolean(fulfillmentContract)||supportsFazerCardsMapping(mapping))===true;const preCommercial=preCommercialReadinessResolver?preCommercialReadinessResolver({selection,mapping,supplier,product,pkg,offer,supplierProduct,availability,customerMarket:market,fulfillmentContract,adapter,inputContractReady,offerSupported}):assessExistingPreparedRoute({mapping,supplier,supplierProduct,offer,availability,canonicalProduct:product,canonicalPackages:pkg?[pkg]:[]},[market],{adapterResolver:()=>adapter,processorSupportResolver:()=>offerSupported});return{selection,mapping,supplier,product,pkg,offer,supplierProduct,fulfillmentContract,availability,conflicts,adapter,customerMarket:market,inputContractReady,offerSupported,preCommercial};}
    async function inspect(input){const state=await load(input),blockers=activationBlockers(state),lock=sourceLock(state),active=state.mapping.enabled===true&&state.mapping.executionMode==="API"&&state.mapping.productionRole==="PRIMARY";return{ready:blockers.length===0,blockers,sourceLock:lock,state:active?"ROUTE_ACTIVE":blockers.length?"BLOCKED":"READY",marketCompatibility:supplierMarketCompatibility(state.mapping.region,state.customerMarket),customerInput:state.inputContractReady?{verified:true}:{verified:false,reviewable:false,supplierCatalogProductId:id(state.supplierProduct)},supplierIdentity:{supplierCode:state.mapping.supplierCode,supplierProductCode:state.mapping.supplierProductCode,supplierMarket:state.mapping.region,supplierCatalogProductId:id(state.supplierProduct)}};}
    async function activate(input,context={}){if(upper(context.actor?.role)!=="OWNER")throw new StorePackageActivationError("OWNER_ACTIVATION_REQUIRED","Only the Owner can activate a selected selling route.",403);if(input.confirmed!==true)throw new StorePackageActivationError("ACTIVATION_CONFIRMATION_REQUIRED","Confirm Start Selling route activation.",400);return transaction(async session=>{const state=await load(input,session),actualLock=sourceLock(state);assertSourceLock(input.sourceLock,actualLock);const blockers=activationBlockers(state);if(blockers.length)throw new StorePackageActivationError("STORE_PACKAGE_ACTIVATION_BLOCKED","This selected route is not technically prepared for activation.",409,{blockers});const already=state.mapping.enabled===true&&state.mapping.executionMode==="API"&&state.mapping.productionRole==="PRIMARY";if(already)return{changed:false,state:"ROUTE_ACTIVE",sourceLock:actualLock};const mapping=await M.Mapping.findById(state.mapping._id).session(session);mapping.enabled=true;mapping.productionRole="PRIMARY";await mapping.save({session});await writeAdminAudit({actor:context.actor,req:context.req,action:ADMIN_AUDIT_ACTIONS.STORE_PACKAGE_ACTIVATED,resourceType:"SupplierProductMapping",resourceId:id(mapping),metadata:{productCode:mapping.productCode,packageCode:mapping.packageCode,supplierCode:mapping.supplierCode,supplierMarket:mapping.region,customerMarket:state.customerMarket,routeActivated:true,publicationChanged:false,storefrontVisibilityChanged:false},session});return{changed:true,state:"ROUTE_ACTIVE",mappingId:id(mapping),publicationChanged:false,storefrontVisibilityChanged:false}});}
    async function activateSelection(input,context={}){if(upper(context.actor?.role)!=="OWNER")throw new StorePackageActivationError("OWNER_ACTIVATION_REQUIRED","Only the Owner can activate selected selling routes.",403);if(input.confirmed!==true||!Array.isArray(input.targets)||!input.targets.length)throw new StorePackageActivationError("ACTIVATION_CONFIRMATION_REQUIRED","Review and confirm Start Selling route activation.",400);return transaction(async session=>{const states=[];for(const target of input.targets){const state=await load({selectionId:input.selectionId,mappingId:target.mappingId,customerMarket:target.customerMarket},session);assertSourceLock(target.sourceLock,sourceLock(state));const blockers=activationBlockers(state);if(blockers.length)throw new StorePackageActivationError("STORE_PACKAGE_ACTIVATION_BLOCKED","This selected route is not technically prepared for activation.",409,{packageCode:state.mapping.packageCode,customerMarket:state.customerMarket,blockers});states.push(state)}const byMapping=new Map();for(const state of states)byMapping.set(id(state.mapping),state);for(const state of byMapping.values()){const mapping=await M.Mapping.findById(state.mapping._id).session(session);mapping.enabled=true;mapping.productionRole="PRIMARY";await mapping.save({session})}await writeAdminAudit({actor:context.actor,req:context.req,action:ADMIN_AUDIT_ACTIONS.STORE_PACKAGE_ACTIVATED,resourceType:"StoreCatalogSelection",resourceId:input.selectionId,metadata:{productCode:states[0].selection.productCode,packageCount:byMapping.size,routeTargets:states.length,customerMarkets:[...new Set(states.map(state=>state.customerMarket))].sort(),publicationChanged:false,storefrontVisibilityChanged:false},session});return{changed:true,state:"ROUTES_ACTIVE",activatedMappings:byMapping.size,publicationChanged:false,storefrontVisibilityChanged:false}})}
    return{inspect,activate,activateSelection};
}
const service=createStorePackageActivationService();
module.exports={StorePackageActivationError,approvedCost,exactInputContract,activationBlockers,sourceLock,assertSourceLock,createStorePackageActivationService,inspectStorePackageActivation:service.inspect,activateStorePackage:service.activate,activateStoreCatalogSelection:service.activateSelection};
