const SUPPLIER_FAILURE_CATEGORIES = Object.freeze({
    OUT_OF_STOCK: "SUPPLIER_OUT_OF_STOCK",
    BALANCE_INSUFFICIENT: "SUPPLIER_BALANCE_INSUFFICIENT",
    AUTH_ERROR: "SUPPLIER_AUTH_ERROR",
    TIMEOUT: "SUPPLIER_TIMEOUT",
    RATE_LIMIT: "SUPPLIER_RATE_LIMIT",
    PACKAGE_INVALID: "SUPPLIER_PACKAGE_INVALID",
    SERVICE_UNAVAILABLE: "SUPPLIER_SERVICE_UNAVAILABLE",
    REJECTED: "SUPPLIER_REJECTED",
    UNKNOWN_ERROR: "SUPPLIER_UNKNOWN_ERROR"
});

const EXPLICIT_CODE_CATEGORY = new Map([
    ["WONDD_PACKAGE_OUT_OF_STOCK", SUPPLIER_FAILURE_CATEGORIES.OUT_OF_STOCK],
    ["FAZERCARDS_OUT_OF_STOCK", SUPPLIER_FAILURE_CATEGORIES.OUT_OF_STOCK],
    ["OUT_OF_STOCK", SUPPLIER_FAILURE_CATEGORIES.OUT_OF_STOCK],
    ["WONDD_INSUFFICIENT_BALANCE", SUPPLIER_FAILURE_CATEGORIES.BALANCE_INSUFFICIENT],
    ["WONDD_ACCOUNT_CONFIGURATION_ERROR", SUPPLIER_FAILURE_CATEGORIES.AUTH_ERROR],
    ["WONDD_IP_ALLOWLIST_ERROR", SUPPLIER_FAILURE_CATEGORIES.AUTH_ERROR],
    ["FAZERCARDS_HTTP_401", SUPPLIER_FAILURE_CATEGORIES.AUTH_ERROR],
    ["FAZERCARDS_HTTP_403", SUPPLIER_FAILURE_CATEGORIES.AUTH_ERROR],
    ["WONDD_TRANSPORT_ERROR", SUPPLIER_FAILURE_CATEGORIES.TIMEOUT],
    ["FAZERCARDS_TRANSPORT_ERROR", SUPPLIER_FAILURE_CATEGORIES.TIMEOUT],
    ["WONDD_STATUS_CHECK_ERROR", SUPPLIER_FAILURE_CATEGORIES.TIMEOUT],
    ["FAZERCARDS_STATUS_CHECK_ERROR", SUPPLIER_FAILURE_CATEGORIES.TIMEOUT],
    ["FAZERCARDS_HTTP_429", SUPPLIER_FAILURE_CATEGORIES.RATE_LIMIT],
    ["WONDD_PACKAGE_MAPPING_INVALID", SUPPLIER_FAILURE_CATEGORIES.PACKAGE_INVALID],
    ["WONDD_SERVICE_MAPPING_INVALID", SUPPLIER_FAILURE_CATEGORIES.PACKAGE_INVALID],
    ["WONDD_SERVICE_UNAVAILABLE", SUPPLIER_FAILURE_CATEGORIES.SERVICE_UNAVAILABLE]
]);

function normalizedCode(value) {
    return String(value || "").trim().toUpperCase().slice(0, 80);
}

function classifySupplierFailure(result = {}) {
    const failureCode = normalizedCode(result.failureCode);
    const providerStatus = normalizedCode(result.providerStatus);
    const category = EXPLICIT_CODE_CATEGORY.get(failureCode)
        || EXPLICIT_CODE_CATEGORY.get(providerStatus)
        || SUPPLIER_FAILURE_CATEGORIES.UNKNOWN_ERROR;

    return {
        category,
        failureCode,
        providerStatus,
        outOfStock: category === SUPPLIER_FAILURE_CATEGORIES.OUT_OF_STOCK
    };
}

module.exports = {
    SUPPLIER_FAILURE_CATEGORIES,
    classifySupplierFailure
};
