const CATALOG_CATEGORIES = Object.freeze([
    "MOBILE_GAME_TOPUP",
    "PC_GAME",
    "GIFT_CARD",
    "DIGITAL_SERVICE",
    "MOBILE_RECHARGE",
    "ENTERTAINMENT"
]);

const HOMEPAGE_FLAGS = Object.freeze(["POPULAR", "NEW", "TRENDING", "FEATURED"]);
const HOMEPAGE_SECTIONS = Object.freeze([
    "POPULAR_GAME_CARDS",
    "POPULAR_GAME_TOPUP",
    "POPULAR_PC_GAMES",
    "POPULAR_GIFT_CARDS",
    "NEW_GAME_CARDS",
    "NEW_GAME_TOPUP",
    "DIGITAL_SERVICES"
]);
const CATALOG_LIFECYCLE = Object.freeze(["ACTIVE", "COMING_SOON"]);
const COMMERCE_STATES = Object.freeze(["PURCHASABLE", "COMING_SOON", "TEMPORARILY_UNAVAILABLE", "HIDDEN"]);

module.exports = { CATALOG_CATEGORIES, HOMEPAGE_FLAGS, HOMEPAGE_SECTIONS, CATALOG_LIFECYCLE, COMMERCE_STATES };
