"use strict";
const crypto=require("crypto"),mongoose=require("mongoose");
const Supplier=require("../../models/Supplier"),Product=require("../../models/SupplierCatalogProduct"),Offer=require("../../models/SupplierCatalogOffer"),Availability=require("../../models/SupplierOfferAvailability"),Mapping=require("../../models/SupplierProductMapping"),CatalogProduct=require("../../models/CatalogProduct"),CatalogPackage=require("../../models/CatalogPackage"),Selection=require("../../models/StoreCatalogSelection"),Audit=require("../../models/AdminAuditLog");
const {canonicalJson}=require("./supplierCatalogNormalization"),{sourceLock}=require("./supplierCatalogReconciliationService"),{deterministicProductCode}=require("./supplierCanonicalProductAuthorityService"),{evaluateAddProductOffer,verifiedEligibility}=require("./addProductPreparabilityService"),{normalizeSupplierMarket}=require("../../constants/supplierMarkets"),{contractFromSupplierCatalog}=require("../suppliers/fazercardsFulfillmentContractService");
const clean=v=>String(v==null?"":v).trim(),upper=v=>clean(v).toUpperCase(),lower=v=>clean(v).toLowerCase(),id=v=>clean(v?._id||v),sha=v=>crypto.createHash("sha256").update(typeof v==="string"?v:canonicalJson(v)).digest("hex");
class AddProductFinalizationError extends Error{constructor(code,message,statusCode=409,details={}){super(message);this.name="AddProductFinalizationError";this.code=code;this.statusCode=statusCode;this.details=details}}
function packageCode(productCode,offer){const semantic=clean(offer.normalizedSemantics?.canonicalCode||offer.normalizedSemantics?.denomination||offer.supplierOfferName||offer.supplierOfferCode).toUpperCase().replace(/[^A-Z0-9]+/g,"_").replace(/^_+|_+$/g,"").slice(0,40)||"PACKAGE",suffix=sha(`${productCode}|${offer.catalogNamespace}|${offer.supplierProductCode}|${offer.supplierOfferCode}`).slice(0,16).toUpperCase();return`${upper(productCode)}_${semantic}_${suffix}`.slice(0,80)}
const sessionize=(query,session)=>session?query.session(session):query;
async function loadContext(input={},session=null){
 const product=await sessionize(Product.findById(input.supplierCatalogProductId),session).lean();if(!product)throw new AddProductFinalizationError("SUPPLIER_PRODUCT_NOT_FOUND","Supplier product is unavailable.",404);
 const supplier=await sessionize(Supplier.findById(product.supplierId),session).lean();if(!supplier)throw new AddProductFinalizationError("SUPPLIER_UNAVAILABLE","Supplier is unavailable.",404);
 const offers=await sessionize(Offer.find({supplierCatalogProductId:product._id}).sort({supplierOfferCode:1}),session).lean();
 const availability=await sessionize(Availability.find({supplierCatalogOfferId:{$in:offers.map(row=>row._id)}}),session).lean();
 const mappings=await sessionize(Mapping.find({supplierId:product.supplierId,$or:[{supplierCatalogOfferId:{$in:offers.map(row=>row._id)}},{supplierProductCode:product.supplierProductCode}],archivedAt:null}),session).lean();
 const authorityCode=lower(product.metadata?.onboardingCanonicalProduct?.productCode),mappedCodes=[...new Set(mappings.map(row=>lower(row.productCode)).filter(Boolean))];
 if(mappedCodes.length>1)throw new AddProductFinalizationError("CANONICAL_PRODUCT_IDENTITY_CONFLICT","Supplier product has conflicting canonical authority.");
 const durableProductCode=lower(mappedCodes[0]||authorityCode||deterministicProductCode(product));
 if(input.productCode&&lower(input.productCode)!==durableProductCode)throw new AddProductFinalizationError("CANONICAL_PRODUCT_IDENTITY_CONFLICT","Requested logical product does not match durable supplier authority.");
 const productCode=durableProductCode;
 const canonical=await sessionize(CatalogProduct.findOne({productCode,deletedAt:null}),session).lean();
 const packages=await sessionize(CatalogPackage.find({productCode,deletedAt:null}),session).lean();
 const selection=await sessionize(Selection.findOne({productCode,supplierMarket:normalizeSupplierMarket(product.supplierMarketCode)}),session).lean();
 return{product,supplier,offers,availability,mappings,productCode,canonical,packages,selection};
}
function makePlan(context,input={}){const markets=[...new Set((input.customerMarkets||input.sellingRegions||[]).map(upper).filter(value=>["TH","MM"].includes(value)))].sort(),availabilityBy=new Map(context.availability.map(row=>[id(row.supplierCatalogOfferId),row])),mappingBy=new Map(context.mappings.map(row=>[id(row.supplierCatalogOfferId),row])),packageBy=new Map(context.packages.map(row=>[upper(row.packageCode),row])),newCanonicalProduct=!context.canonical;const offers=context.offers.map(offer=>{const mapping=mappingBy.get(id(offer)),code=mapping?.packageCode||packageCode(context.productCode,offer),assessment=evaluateAddProductOffer({supplier:context.supplier,product:context.product,offer,availability:availabilityBy.get(id(offer)),mapping,canonicalPackage:packageBy.get(upper(code)),customerMarkets:markets,newCanonicalProduct});return{supplierCatalogOfferId:id(offer),supplierOfferCode:offer.supplierOfferCode,name:offer.supplierOfferName||offer.rawName||offer.supplierOfferCode,packageCode:upper(code),mappingId:id(mapping),sourceLock:sourceLock({offer,product:context.product,availability:availabilityBy.get(id(offer))}),...assessment}});const body={schemaVersion:1,supplierCatalogProductId:id(context.product),supplierId:id(context.supplier),supplierCode:upper(context.supplier.supplierCode),supplierProductCode:context.product.supplierProductCode,supplierMarket:normalizeSupplierMarket(context.product.supplierMarketCode),productCode:context.productCode,productName:context.canonical?.name||context.product.displayName||context.product.rawName,existingCanonical:Boolean(context.canonical),customerMarkets:markets,expectedDecisionVersion:Number(context.selection?.decisionVersion||0),productSource:{sourceHash:context.product.rawSnapshotHash,sourceRevision:context.product.sourceRevision||context.product.rawSnapshotHash,lastChangedAt:new Date(context.product.lastChangedAt).toISOString()},offers};return{...body,planHash:sha(body)}}
async function generateAddProductPlan(input={}){return makePlan(await loadContext(input),input)}
function sameLock(expected,current){for(const key of ["supplierCatalogOfferId","supplierId","catalogNamespace","supplierProductCode","supplierOfferCode","sourceOfferHash","sourceOfferRevision","sourceLastChangedAt","sourceSemanticHash","sourceProductEvidenceHash","sourceCostHash"])if(clean(expected?.[key])!==clean(current?.[key]))return false;return true}
async function finalizeAddProduct(input={},context={}){if(process.env.SUPPLIER_PRODUCT_ONBOARDING_MUTATIONS_ENABLED!=="true")throw new AddProductFinalizationError("SUPPLIER_PRODUCT_ONBOARDING_MUTATIONS_DISABLED","Add Product mutations are disabled.",403);if(upper(context.actor?.role)!=="OWNER")throw new AddProductFinalizationError("OWNER_REQUIRED","Only the Owner may add a product.",403);if(!clean(input.planHash)||!Array.isArray(input.selectedOfferIds)||!input.selectedOfferIds.length)throw new AddProductFinalizationError("ADD_PRODUCT_SELECTION_REQUIRED","Choose at least one preparable package.",400);
 const transaction=context.transaction||(async fn=>{const session=await mongoose.startSession();try{let value;await session.withTransaction(async()=>{value=await fn(session)});return value}finally{await session.endSession()}});
 const committedReplay=await Selection.findOne({"provenance.planHash":input.planHash}).lean();
 if(committedReplay)return{selection:committedReplay,productCode:committedReplay.productCode,packageCount:committedReplay.packages.length,idempotentReplay:true,dailyPricing:{supplierId:id(committedReplay.supplierId),productCode:committedReplay.productCode}};
 try{return await transaction(async session=>{const state=await loadContext(input,session),plan=makePlan(state,input);if(plan.planHash!==input.planHash)throw new AddProductFinalizationError("STALE_SOURCE","Supplier information changed. Refresh and review again.");if(Number(input.expectedDecisionVersion||0)!==Number(plan.expectedDecisionVersion))throw new AddProductFinalizationError("ADD_PRODUCT_VERSION_CONFLICT","Store Catalog selection changed. Refresh and review again.");if(state.selection?.provenance?.planHash===plan.planHash)return{selection:state.selection,productCode:plan.productCode,packageCount:state.selection.packages.length,idempotentReplay:true};const selected=new Set(input.selectedOfferIds.map(clean)),rows=plan.offers.filter(row=>selected.has(row.supplierCatalogOfferId));if(rows.length!==selected.size||rows.some(row=>!row.selectable))throw new AddProductFinalizationError("ADD_PRODUCT_PACKAGE_NOT_PREPARABLE","One or more packages are no longer preparable.",{statusCode:409});
 let canonical=state.canonical;if(!canonical){canonical=(await CatalogProduct.create([{productCode:plan.productCode,name:plan.productName,enabled:true,commerceState:"HIDDEN",publicDiscoveryEnabled:false,homepageEnabled:false,supportedRegions:[],source:"admin",metadata:{preparedFromSupplierCatalogProductId:state.product._id,onboardingPrepared:true,onboardingPlanHash:plan.planHash}}],{session}))[0].toObject();await Product.updateOne({_id:state.product._id,rawSnapshotHash:state.product.rawSnapshotHash},{$set:{"metadata.onboardingCanonicalProduct":{authoritative:true,authorityType:"OWNER_CREATE_NEW_CANONICAL_PRODUCT",productCode:plan.productCode,supplierCatalogProductId:id(state.product),supplierId:id(state.supplier),catalogNamespace:state.product.catalogNamespace,supplierProductCode:state.product.supplierProductCode,sourceHash:state.product.rawSnapshotHash,sourceRevision:state.product.sourceRevision||state.product.rawSnapshotHash,idempotencyKey:plan.planHash}}},{session,runValidators:true})}
 const committed=[];for(const row of rows){const offer=state.offers.find(value=>id(value)===row.supplierCatalogOfferId),availability=state.availability.find(value=>id(value.supplierCatalogOfferId)===id(offer));if(!sameLock(row.sourceLock,sourceLock({offer,product:state.product,availability})))throw new AddProductFinalizationError("STALE_SOURCE","Supplier package changed. Refresh and review again.");let pkg=await sessionize(CatalogPackage.findOne({productCode:plan.productCode,packageCode:row.packageCode}),session).lean();if(!pkg)pkg=(await CatalogPackage.create([{productCode:plan.productCode,packageCode:row.packageCode,name:row.name,enabled:true,source:"admin",metadata:{entitlementSemantics:offer.normalizedSemantics||{},supplierCatalogAdoption:{supplierCatalogOfferId:offer._id,supplierProductCode:offer.supplierProductCode,supplierOfferCode:offer.supplierOfferCode,planHash:plan.planHash}}}],{session}))[0].toObject();let mapping=await sessionize(Mapping.findOne({supplierId:state.supplier._id,supplierProductCode:offer.supplierProductCode,supplierPackageCode:offer.supplierOfferCode,region:plan.supplierMarket,archivedAt:null}),session).lean();if(!mapping){const draft={supplierId:state.supplier._id,supplierCode:plan.supplierCode,productCode:plan.productCode,packageCode:row.packageCode,supplierProductCode:offer.supplierProductCode,supplierPackageCode:offer.supplierOfferCode,supplierCatalogOfferId:offer._id,supplierDisplayName:row.name,region:plan.supplierMarket,enabled:false,productionRole:"DISABLED",executionMode:"API"},contract=contractFromSupplierCatalog({mapping:draft,offer,supplierProduct:state.product,supplierCode:plan.supplierCode}),eligibility=verifiedEligibility(state.product,null);draft.supplierMarketEvidence={normalizedMarket:plan.supplierMarket,supplierMarketCode:upper(state.product.supplierMarketCode),marketClassification:"AUTHORITATIVE",restrictions:state.product.restrictions||[],evidenceCode:"SOURCE_LOCKED_SUPPLIER_CATALOG",sourceProductHash:state.product.rawSnapshotHash};draft.fulfillmentEligibility=eligibility;draft.mappingMetadata={fulfillmentContract:contract,technicalPreparation:true,onboardingPlanHash:plan.planHash,readiness:{supplierMapped:true,pricingReady:false,inputReady:true,validationReady:true,fulfillmentReady:true,storefrontReady:false}};mapping=(await Mapping.create([draft],{session}))[0].toObject();await Offer.updateOne({_id:offer._id,rawSnapshotHash:offer.rawSnapshotHash},{$set:{reconciliationState:"EXACT_CANONICAL_MATCH",reconciliationEvidence:{code:"ADD_PRODUCT_SOURCE_LOCKED_AUTHORITY",canonicalProductCode:plan.productCode,canonicalPackageCode:row.packageCode,distinctEntitlement:true,planHash:plan.planHash}}},{session,runValidators:true})}committed.push({packageCode:row.packageCode,supplierProductMappingId:mapping._id})}
 const now=new Date(),selection=await Selection.findOneAndUpdate({productCode:plan.productCode,supplierMarket:plan.supplierMarket},{$set:{productCode:plan.productCode,supplierId:state.supplier._id,supplierCode:plan.supplierCode,supplierMarket:plan.supplierMarket,sellingRegions:plan.customerMarkets,visibleRegions:[],packages:committed.sort((a,b)=>a.packageCode.localeCompare(b.packageCode)),status:"ACTIVE",decisionVersion:Number(state.selection?.decisionVersion||0)+1,selectedBy:context.actor.username||"owner",selectedAt:now,provenance:{source:"ADD_PRODUCT_FINAL",sourceHash:state.product.rawSnapshotHash,planHash:plan.planHash,reversible:true}}},{new:true,upsert:true,runValidators:true,setDefaultsOnInsert:true,session}).lean();await Audit.create([{actorAdminId:context.actor?._id||context.actor?.id||null,actorUsernameSnapshot:context.actor?.username||"",actorRoleSnapshot:context.actor?.role||"",action:"ADD_PRODUCT_FINALIZED",resourceType:"StoreCatalogSelection",resourceId:id(selection),requestId:clean(context.requestId),metadata:{planHash:plan.planHash,productCode:plan.productCode,supplierId:plan.supplierId,selectedOfferIds:[...selected].sort(),packageCount:committed.length,publicationWrites:0,priceWrites:0,packageSupplierSelectionWrites:0,primaryAssignments:0,supplierCalls:0}}],{session});return{selection,productCode:plan.productCode,packageCount:committed.length,idempotentReplay:false,dailyPricing:{supplierId:plan.supplierId,productCode:plan.productCode}}})}catch(error){if(error?.code===11000){const replay=await Selection.findOne({"provenance.planHash":input.planHash}).lean();if(replay)return{selection:replay,productCode:replay.productCode,packageCount:replay.packages.length,idempotentReplay:true,dailyPricing:{supplierId:id(replay.supplierId),productCode:replay.productCode}}}throw error}}
module.exports=Object.freeze({AddProductFinalizationError,packageCode,loadContext,makePlan,generateAddProductPlan,finalizeAddProduct});
