"use strict";
const crypto=require("crypto");
const {canonicalJson}=require("./supplierCatalogNormalization");
const {resolveFamilyForServiceCode}=require("../suppliers/wonddCatalogConfig");
const NAMESPACES=Object.freeze({FAZERCARDS:"FAZERCARDS_RESELLER_CATALOG",WONDD:"WONDD_PACKAGE_CATALOG"});
const clean=x=>String(x==null?"":x).trim(),id=x=>clean(x?._id||x),sha=x=>crypto.createHash("sha256").update(canonicalJson(x)).digest("hex");
function withoutReference(mapping){const value={...mapping};delete value.supplierCatalogOfferId;return value}
function mappingBusinessProjection(mapping){return withoutReference(typeof mapping.toObject==="function"?mapping.toObject():mapping)}
function mappingBusinessHash(mappings){return sha(mappings.map(mappingBusinessProjection).sort((a,b)=>id(a).localeCompare(id(b))))}
function mappingPrecondition(mapping){const value=typeof mapping.toObject==="function"?mapping.toObject():mapping;return{_id:id(value),supplierId:id(value.supplierId),supplierCode:clean(value.supplierCode),productCode:clean(value.productCode),packageCode:clean(value.packageCode),supplierProductCode:clean(value.supplierProductCode),supplierPackageCode:clean(value.supplierPackageCode),productionRole:clean(value.productionRole),fulfillmentEligibility:value.fulfillmentEligibility||null,mappingMetadata:value.mappingMetadata||{},supplierCostAuthority:value.supplierCostAuthority||{},executionMode:clean(value.executionMode),enabled:value.enabled===true,archivedAt:value.archivedAt||null,supplierCatalogOfferId:id(value.supplierCatalogOfferId),updatedAt:value.updatedAt||null}}
function preconditionHash(mapping){return sha(mappingPrecondition(mapping))}
function providerIdentity(mapping){if(mapping.supplierCode==="FAZERCARDS")return{namespace:NAMESPACES.FAZERCARDS,supplierProductCode:clean(mapping.supplierProductCode),supplierOfferCode:clean(mapping.supplierPackageCode),evidence:"EXACT_FAZERCARDS_CATEGORY_OFFER_IDENTITY"};if(mapping.supplierCode==="WONDD"){try{const authority=resolveFamilyForServiceCode(mapping.supplierProductCode);return{namespace:NAMESPACES.WONDD,supplierProductCode:authority.serviceId,supplierOfferCode:clean(mapping.supplierPackageCode),evidence:"WONDD_CONFIG_SERVICECODE_TO_SERVICEID_PLUS_PACKCODE"}}catch(error){return{error:error.code||"WONDD_SERVICE_CODE_UNKNOWN"}}}return{error:"UNSUPPORTED_SUPPLIER_CATALOG"}}
function offerKey(supplierId,namespace,product,offer){return`${id(supplierId)}/${namespace}/${clean(product)}/${clean(offer)}`}
function buildOfferIndex(offers){const index=new Map();for(const offer of offers){const key=offerKey(offer.supplierId,offer.catalogNamespace,offer.supplierProductCode,offer.supplierOfferCode);if(!index.has(key))index.set(key,[]);index.get(key).push(offer)}return index}
function classifyMapping(mapping,index){const identity=providerIdentity(mapping);if(identity.error)return{classification:identity.error==="UNSUPPORTED_SUPPLIER_CATALOG"?"UNSUPPORTED_SUPPLIER_CATALOG":"NO_CATALOG_OFFER",identity};const matches=index.get(offerKey(mapping.supplierId,identity.namespace,identity.supplierProductCode,identity.supplierOfferCode))||[];if(matches.length===0)return{classification:"NO_CATALOG_OFFER",identity};if(matches.length>1)return{classification:"AMBIGUOUS_CATALOG_OFFER",identity,matches:matches.map(x=>id(x))};const offer=matches[0],current=id(mapping.supplierCatalogOfferId);if(current&&current===id(offer))return{classification:"ALREADY_LINKED_CORRECTLY",identity,offer};if(current&&current!==id(offer))return{classification:"ALREADY_LINKED_CONFLICT",identity,offer,current};return{classification:"EXACT_ONE_CATALOG_OFFER",identity,offer}}
function buildPlan({mappings,offers,migrationId,createdAt}){const index=buildOfferIndex(offers),audit=[],proposed=[];for(const mapping of mappings){const resolved=classifyMapping(mapping,index),base={mappingId:id(mapping),supplierId:id(mapping.supplierId),supplierCode:mapping.supplierCode,productCode:mapping.productCode,packageCode:mapping.packageCode,providerProductIdentity:mapping.supplierProductCode,providerOfferIdentity:mapping.supplierPackageCode,classification:resolved.classification};audit.push(base);if(resolved.classification==="EXACT_ONE_CATALOG_OFFER")proposed.push({...base,resolvedSupplierCatalogOfferId:id(resolved.offer),catalogNamespace:resolved.identity.namespace,supplierProductIdentity:resolved.identity.supplierProductCode,supplierOfferIdentity:resolved.identity.supplierOfferCode,resolutionEvidence:resolved.identity.evidence,reviewedUpdatedAt:mapping.updatedAt||null,preconditionHash:preconditionHash(mapping)})}
const counts=audit.reduce((a,x)=>(a[x.classification]=(a[x.classification]||0)+1,a),{}),supplierBreakdown=audit.reduce((a,x)=>{a[x.supplierCode]??={total:0,linkable:0,skipped:0,conflicts:0};a[x.supplierCode].total++;if(x.classification==="EXACT_ONE_CATALOG_OFFER")a[x.supplierCode].linkable++;else{a[x.supplierCode].skipped++;if(x.classification.includes("CONFLICT")||x.classification.includes("AMBIGUOUS"))a[x.supplierCode].conflicts++}return a},{}),mappingIdentityHash=sha(proposed.map(x=>[x.mappingId,x.supplierId,x.providerProductIdentity,x.providerOfferIdentity]).sort()),resolvedOfferIdentityHash=sha(proposed.map(x=>[x.resolvedSupplierCatalogOfferId,x.catalogNamespace,x.supplierProductIdentity,x.supplierOfferIdentity]).sort()),planHash=sha(proposed.map(x=>[x.mappingId,x.resolvedSupplierCatalogOfferId,x.preconditionHash]).sort());return{migrationId,createdAt,mappingCount:mappings.length,linkableCount:proposed.length,skippedCount:mappings.length-proposed.length,conflictCount:(counts.AMBIGUOUS_CATALOG_OFFER||0)+(counts.ALREADY_LINKED_CONFLICT||0),classificationCounts:counts,supplierBreakdown,planHash,mappingIdentityHash,resolvedOfferIdentityHash,audit,proposed}}
async function validatePlan(plan,{Mapping,Offer}){const ids=plan.proposed.map(x=>x.mappingId),offerIds=plan.proposed.map(x=>x.resolvedSupplierCatalogOfferId),mappings=await Mapping.find({_id:{$in:ids}}).lean(),offers=await Offer.find({_id:{$in:offerIds}}).lean(),mappingById=new Map(mappings.map(x=>[id(x),x])),offerById=new Map(offers.map(x=>[id(x),x]));for(const row of plan.proposed){const mapping=mappingById.get(row.mappingId);if(!mapping||preconditionHash(mapping)!==row.preconditionHash)throw Object.assign(new Error(`Stale mapping precondition: ${row.mappingId}`),{code:"STALE_MAPPING_PRECONDITION"});const offer=offerById.get(row.resolvedSupplierCatalogOfferId);if(!offer)throw Object.assign(new Error(`Missing catalog offer: ${row.resolvedSupplierCatalogOfferId}`),{code:"MISSING_CATALOG_OFFER"});if(id(offer.supplierId)!==row.supplierId||offer.catalogNamespace!==row.catalogNamespace||offer.supplierProductCode!==row.supplierProductIdentity||offer.supplierOfferCode!==row.supplierOfferIdentity)throw Object.assign(new Error(`Catalog offer identity conflict: ${row.resolvedSupplierCatalogOfferId}`),{code:"CATALOG_OFFER_PRECONDITION_CONFLICT"})}return{mappings,offers}}
async function applyPlan(plan,{Mapping,Offer}){await validatePlan(plan,{Mapping,Offer});let linked=0;for(const row of plan.proposed){const result=await Mapping.updateOne({_id:row.mappingId,updatedAt:row.reviewedUpdatedAt,supplierId:row.supplierId,supplierCode:row.supplierCode,productCode:row.productCode,packageCode:row.packageCode,supplierProductCode:row.providerProductIdentity,supplierPackageCode:row.providerOfferIdentity,$or:[{supplierCatalogOfferId:null},{supplierCatalogOfferId:{$exists:false}}]},{$set:{supplierCatalogOfferId:row.resolvedSupplierCatalogOfferId}},{runValidators:true,timestamps:false});if(result.modifiedCount!==1)throw Object.assign(new Error(`Conditional mapping update conflict: ${row.mappingId}`),{code:"CONDITIONAL_UPDATE_CONFLICT"});linked++}return{linked}}
module.exports=Object.freeze({NAMESPACES,mappingBusinessProjection,mappingBusinessHash,mappingPrecondition,preconditionHash,providerIdentity,offerKey,buildOfferIndex,classifyMapping,buildPlan,validatePlan,applyPlan,sha});
