"use strict";
const Product=require("../../models/SupplierCatalogProduct"),Offer=require("../../models/SupplierCatalogOffer"),Availability=require("../../models/SupplierOfferAvailability"),Run=require("../../models/SupplierCatalogIngestionRun"),Observation=require("../../models/SupplierCatalogCostObservation"),{observedCostHash,effectiveRevision}=require("./supplierCostComparisonService");
const omit=(value,keys)=>Object.fromEntries(Object.entries(value).filter(([key])=>!keys.includes(key)));
function createSupplierCatalogMongoRepositories(models={}){const P=models.Product||Product,O=models.Offer||Offer,A=models.Availability||Availability,R=models.Run||Run,H=models.Observation||Observation;return{
 products:{async upsert(input){const identity={supplierId:input.supplierId,catalogNamespace:input.catalogNamespace,supplierProductCode:input.supplierProductCode},set=omit(input,["_id","operation","firstSeenAt","supplierId","catalogNamespace","supplierProductCode"]);return P.findOneAndUpdate(identity,{$set:set,$setOnInsert:{...identity,firstSeenAt:input.firstSeenAt}},{returnDocument:"after",upsert:true,runValidators:true,setDefaultsOnInsert:true});}},
 offers:{async upsert(input){const identity={supplierId:input.supplierId,catalogNamespace:input.catalogNamespace,supplierProductCode:input.supplierProductCode,supplierOfferCode:input.supplierOfferCode},set=omit(input,["_id","operation","availability","firstSeenAt","supplierId","catalogNamespace","supplierProductCode","supplierOfferCode"]);return O.findOneAndUpdate(identity,{$set:set,$setOnInsert:{...identity,firstSeenAt:input.firstSeenAt}},{returnDocument:"after",upsert:true,runValidators:true,setDefaultsOnInsert:true});}},
 availability:{async upsert(input){const identity={supplierCatalogOfferId:input.supplierCatalogOfferId};return A.findOneAndUpdate(identity,{$set:omit(input,["_id"])},{returnDocument:"after",upsert:true,runValidators:true,setDefaultsOnInsert:true});}},
 observations:{async append({offer,ingestionRunId=null}){if(!offer?.supplierCost)return null;const observedCostHashValue=observedCostHash(offer),doc={supplierCatalogOfferId:offer._id,supplierCatalogProductId:offer.supplierCatalogProductId,supplierId:offer.supplierId,catalogNamespace:offer.catalogNamespace,supplierProductCode:offer.supplierProductCode,supplierOfferCode:offer.supplierOfferCode,amount:offer.supplierCost.amount,currency:offer.supplierCost.currency,observedAt:offer.supplierCost.observedAt,sourceRevision:effectiveRevision(offer),rawSnapshotHash:offer.rawSnapshotHash,observedCostHash:observedCostHashValue,ingestionRunId};return H.findOneAndUpdate({observedCostHash:observedCostHashValue},{$setOnInsert:doc},{returnDocument:"after",upsert:true,runValidators:true,setDefaultsOnInsert:true});}},
 runs:{async start(input){if(typeof input.runKey!=="string"||!input.runKey.trim())throw new TypeError("A deterministic supplier catalog ingestion runKey is required");const identity={supplierId:input.supplierId,catalogNamespace:input.catalogNamespace,runKey:input.runKey};return R.findOneAndUpdate(identity,{$setOnInsert:{...input,...identity}},{returnDocument:"after",upsert:true,runValidators:true,setDefaultsOnInsert:true});},async finalize(id,plan){const completedAt=new Date();return R.findByIdAndUpdate(id,{$set:{status:plan.runStatus,coverageState:plan.coverageState,completedAt,productsObserved:plan.products.length,offersObserved:plan.offers.length,newProducts:plan.products.filter(x=>x.operation==="CREATE").length,newOffers:plan.offers.filter(x=>x.operation==="CREATE").length,changedOffers:plan.offers.filter(x=>x.operation==="UPDATE").length,missingOffers:plan.missing.length,availabilityTransitions:plan.offers.length+plan.missing.length,mappingCoverage:plan.mappingCoverage||{},categoryResults:plan.categoryResults,errors:plan.errors,durationMs:Math.max(0,completedAt.getTime()-new Date(plan.observedAt).getTime()),metadata:{completenessEvidence:plan.completenessEvidence||""}}},{returnDocument:"after",runValidators:true});}}
};}
module.exports=Object.freeze({createSupplierCatalogMongoRepositories});
